# Set the base image to beakerx
FROM beakerx/beakerx:latest

# it's better to be root as this Dockerfile will try to update conda etc.
USER root

ENV PATH /opt/conda/envs/beakerx/bin:$PATH

# copy the config file
COPY jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py

# update pip
RUN pip install --no-cache-dir --upgrade pip

# install rise and cvxpy
RUN conda install -y -n beakerx -c conda-forge rise=5.4.1 cvxpy=1.0.14 && conda clean -y --all

# go back to the standard user
USER $NB_USER

# create the work folder
RUN mkdir -p /home/$NB_USER/work