# Set the base image to beakerx
FROM jupyter/minimal-notebook:45b8529a6bfc

RUN conda config --env --add pinned_packages 'openjdk>8.0.121'
RUN conda install -y -c conda-forge pandas=0.24.1 rise=5.4.1 requests=2.21.0 beakerx=1.3.0 ipywidgets=7.4.2 seaborn=0.9.0 matplotlib=3.0.3
RUN conda install -y -c cvxgrp cvxpy=1.0.21 && conda clean -y --all

COPY jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
